/** 预览版的示例数据。分析内容是手写的，不是模型的输出。 */
import type { Project, RawInput } from "../api";
import { blankRequirement, type Stored } from "../core/persistence";

export const seedProjects: Project[] = [
  {
    id: 1,
    name: "智能门锁（示例）",
    description: "客户是连锁长租公寓运营商，一名管家负责约两百间房的门锁，租客流动频繁。",
    dismissed_probes: [],
  },
];

export const seedInputs: RawInput[] = [
  {
    id: 1,
    project_id: 1,
    source_type: "客户",
    requester: "城南公寓",
    content:
      "门锁开机太慢，指纹识别要等两秒。\n报价比竞品高了一成，希望能给折扣。\n安装说明书看不懂，师傅上门装了一个小时。\n售后响应慢，报修三天没人管。",
    status: "processed",
    error: null,
    created_at: "2026-10-01T09:00:00Z",
  },
  {
    id: 2,
    project_id: 1,
    source_type: "客户",
    requester: "城北公寓",
    content: "指纹开锁慢得受不了。",
    status: "processed",
    error: null,
    created_at: "2026-10-03T09:00:00Z",
  },
];

function make(partial: Partial<Stored> & Pick<Stored, "id" | "title">): Stored {
  return {
    ...blankRequirement(),
    project_id: 1,
    input_id: 1,
    quote_verified: true,
    ...partial,
  };
}

export const seedRequirements: Stored[] = [
  make({
    id: 1,
    title: "走到门口伸手即开，无需停顿",
    description: "住户希望开门是一个连贯动作，不需要停下来等锁反应。",
    source_quote: "门锁开机太慢，指纹识别要等两秒",
    stated_request: "希望指纹识别快一点",
    underlying_problem: "住户到门口时手里常提着东西，等待的两秒里门锁没有任何反馈，会怀疑没识别上而重复按压。",
    reasoning: "材料只说了等两秒，没有说明场景。提东西、重复按压是按常见情况推测的，需要向客户确认。",
    confidence: "medium",
    open_questions: ["等待的两秒里，用户通常会做什么？会重复按吗？", "慢是每次都慢，还是隔一段时间不用后才慢？"],
    demand_type: "strategic",
    category: "quality",
    subcategory: "performance",
    disposition: "next",
    disposition_reason: "影响每天使用，但需要改识别方案，赶不上当前版本。",
    appeals: "performance",
    priority: "high",
    priority_reason: "客户首先提到，且直接影响每天的使用。",
  }),
  make({
    id: 2,
    title: "让客户看得到价差对应的价值",
    description: "客户需要一个能向内部交代的理由，说明为什么值得多付一成。",
    source_quote: "报价比竞品高了一成，希望能给折扣",
    stated_request: "希望给折扣",
    underlying_problem: "客户没有看到与多出的一成价格相对应的价值，所以只能在价格上比较。",
    reasoning: "客户拿竞品报价作比较，说明在他看来两者差不多。降价只是其中一种解法。",
    confidence: "low",
    open_questions: ["对比的是哪家竞品的哪个型号？", "如果价格不变，增加什么会让你愿意接受？"],
    demand_type: "project",
    category: "functional",
    appeals: "price",
    priority_reason: "影响成交，但材料没有说明是否因此丢单。",
  }),
  make({
    id: 3,
    title: "安装师傅第一次装也能快速装对",
    description: "不依赖师傅经验，安装时间可预期。",
    source_quote: "安装说明书看不懂，师傅上门装了一个小时",
    stated_request: "说明书要写得让人看懂",
    underlying_problem: "安装依赖师傅的个人经验，耗时不可控，客户要承担等待时间和上门费用。",
    reasoning: "材料直接给出了后果：装了一个小时。问题不在说明书的文字，而在安装过程本身容易出错。",
    confidence: "high",
    demand_type: "strategic",
    category: "quality",
    subcategory: "maintainability",
    disposition: "current",
    disposition_reason: "已经在增加上门成本，改安装引导即可。",
    appeals: "ease_of_use",
    priority: "high",
    priority_reason: "材料明确描述了耗时后果。",
    status: "confirmed",
  }),
  make({
    id: 4,
    title: "锁出故障时当天能恢复正常进出",
    description: "客户要的是尽快恢复使用，而不只是有人接电话。",
    source_quote: "售后响应慢，报修三天没人管",
    stated_request: "售后响应要快",
    underlying_problem: "门锁出故障意味着进不了家门或门锁不上，客户等不起三天。",
    reasoning: "门锁是进出家门的必经环节，故障的后果比一般家电严重。材料没有说明具体是什么故障。",
    confidence: "medium",
    open_questions: ["报修的是什么故障？当时还能正常开关门吗？"],
    category: "quality",
    subcategory: "reliability",
    disposition: "current",
    disposition_reason: "涉及进出家门，不能拖。",
    appeals: "assurances",
    priority: "high",
    priority_reason: "涉及安全和基本使用。",
  }),
  make({
    id: 5,
    input_id: 2,
    title: "开门不需要等待",
    description: "开锁动作要连贯。",
    source_quote: "指纹开锁慢得受不了",
    stated_request: "希望开锁快一点",
    underlying_problem: "租客在门口等待，体验差。",
    reasoning: "与已有的一条需求说的是同一件事。",
    confidence: "high",
    demand_type: "strategic",
    category: "quality",
    subcategory: "performance",
    disposition: "next",
    disposition_reason: "同已有需求。",
    appeals: "performance",
    priority: "high",
    priority_reason: "第二家客户也在提。",
    duplicate_of_id: 1,
  }),
  make({
    id: 6,
    input_id: null,
    kind: "latent",
    title: "锁在出问题之前先提醒，并能自行恢复",
    description: "住户不想等到进不了门才发现问题。",
    based_on: [4, 3],
    reasoning: "售后慢和安装难都发生在需要人上门的环节。客户抱怨的是上门慢，但更根本的是他不希望落到需要上门的地步。",
    validation_plan: "回访 5 位报修过的客户，问故障发生前有没有征兆、如果提前收到提醒会怎么做。",
    open_questions: ["故障前有没有电量低、反应变慢之类的征兆？"],
    category: "quality",
    subcategory: "reliability",
    appeals: "assurances",
    priority_reason: "依据来自两条高优先级需求，但尚未验证。",
    quote_verified: false,
  }),
];
