"""requirement analysis fields

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-07 03:21:11.949392
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirements', sa.Column('kind', sa.String(length=20), server_default='stated', nullable=False))
    op.add_column('requirements', sa.Column('stated_request', sa.Text(), server_default='', nullable=False))
    op.add_column('requirements', sa.Column('underlying_problem', sa.Text(), server_default='', nullable=False))
    op.add_column('requirements', sa.Column('reasoning', sa.Text(), server_default='', nullable=False))
    op.add_column('requirements', sa.Column('confidence', sa.String(length=10), server_default='low', nullable=False))
    op.add_column('requirements', sa.Column('open_questions', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('requirements', sa.Column('based_on', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('requirements', sa.Column('validation_plan', sa.Text(), server_default='', nullable=False))
    op.add_column('requirements', sa.Column('validation_status', sa.String(length=20), server_default='unverified', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirements', 'validation_status')
    op.drop_column('requirements', 'validation_plan')
    op.drop_column('requirements', 'based_on')
    op.drop_column('requirements', 'open_questions')
    op.drop_column('requirements', 'confidence')
    op.drop_column('requirements', 'reasoning')
    op.drop_column('requirements', 'underlying_problem')
    op.drop_column('requirements', 'stated_request')
    op.drop_column('requirements', 'kind')
    # ### end Alembic commands ###
