"""classification disposition merge requester

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-07 03:52:31.263926
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('dismissed_probes', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('raw_inputs', sa.Column('requester', sa.String(length=100), server_default='', nullable=False))
    op.add_column('requirements', sa.Column('category', sa.String(length=20), server_default='unknown', nullable=False))
    op.add_column('requirements', sa.Column('subcategory', sa.String(length=30), nullable=True))
    op.add_column('requirements', sa.Column('disposition', sa.String(length=20), server_default='undecided', nullable=False))
    op.add_column('requirements', sa.Column('disposition_reason', sa.Text(), server_default='', nullable=False))
    op.add_column('requirements', sa.Column('reject_reason', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirements', 'reject_reason')
    op.drop_column('requirements', 'disposition_reason')
    op.drop_column('requirements', 'disposition')
    op.drop_column('requirements', 'subcategory')
    op.drop_column('requirements', 'category')
    op.drop_column('raw_inputs', 'requester')
    op.drop_column('projects', 'dismissed_probes')
    # ### end Alembic commands ###
